export interface ReferralNode {
  /** Wallet address or user id of this node. */
  address: string;
  username: string;
  /** True if the player has been active (wagered) in the last 30 days. */
  isActive: boolean;
  /** Total wagers generated by this invitee (and, at the root, by the whole team). */
  totalWagers: number;
  /** Referral rewards earned directly from this invitee's activity. */
  rewardsEarned: number;
  /** Tier-2 (second-level) invitees. Empty for a leaf node or the root's
   * direct (tier-1) invitees that haven't invited anyone themselves. */
  children: ReferralNode[];
}

export interface ReferralTreeVisualizerProps {
  treeData: ReferralNode;
  onCopyInviteLink: () => void;
  onInspectUser?: (address: string) => void;
  className?: string;
  testId?: string;
}

export interface TreeNodeItemProps {
  node: ReferralNode;
  depth: number;
  searchQuery: string;
  onInspectUser?: (address: string) => void;
  testId?: string;
}
