use soroban_sdk::contracttype;

/// Aggregated referral-volume summary for a single affiliate.
///
/// Zero-state: all counts/amounts 0, `exists` false when no record found.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferralVolumeSummary {
    /// Whether an affiliate record exists.
    pub exists: bool,
    /// Total number of referred players.
    pub referral_count: u32,
    /// Cumulative volume generated by referrals (token-smallest-unit).
    pub total_volume: i128,
    /// Total commissions earned (before any payouts).
    pub total_commission_earned: i128,
    /// Total commissions already paid out.
    pub total_commission_paid: i128,
    /// Outstanding (unpaid) commission balance.
    pub unpaid_balance: i128,
}

/// Payout eligibility for an affiliate.
///
/// Zero-state: `eligible` false, reason = "no_record" when affiliate is unknown.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PayoutEligibility {
    /// Whether the affiliate is eligible for a payout right now.
    pub eligible: bool,
    /// Unpaid balance available for payout.
    pub claimable_amount: i128,
    /// Minimum balance required before a payout is triggered.
    pub minimum_threshold: i128,
    /// Whether the affiliate account is currently active.
    pub account_active: bool,
}

/// Internal affiliate record stored in persistent storage.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AffiliateRecord {
    pub referral_count: u32,
    pub total_volume: i128,
    pub total_commission_earned: i128,
    pub total_commission_paid: i128,
    pub active: bool,
}
